### ISSUE TITLE
Add a /huntdelay command to change the delay ingame.

### ISSUE THREAD

**Issue by zix3r** [yummypasta/MinecraftManhunt#15]
## Description
Add a /huntdelay command to change the delay ingame. It would be way more efficient and better.

**Comment by yummypasta** [comment]
Thanks for using this plugin and suggesting these features. I'm working on adding them in version 1.2.5 right now!

**Comment by zix3r** [comment]
It's no biggie and also, this is the only plugin I use for playing manhunt, its simply amazing! I also have 1 more suggestion. When Hunters die, they should be automatically given compasses, I think that would make this plugin even more efficient!

**Comment by yummypasta** [comment]
The `setheadstart` command has been added in 57ceb8cb51b24ae19504178ba2ea1764955697c8, and hunters are given compasses on respawn in 7260a88b5092a2ee6c5bf4fb56101b1f01901677. Features available in release 1.3!
