### ISSUE TITLE
Limit times "pirates" track is played

### ISSUE THREAD

**Issue by yummypasta** [yummypasta/MinecraftManhunt#21]
Record the last time the track started playing, and only play it again after a certain interval.

**Comment by zix3r** [comment]
Yes, please do this, the song usually starts and doesnt end for like 5 minutes straight even though we aren't in boats anymore.

**Comment by yummypasta** [comment]
By the way, in commit e78f57e, I added an undocumented config option called `piratesCooldown`. If a `long` number is specified, it will be used as the **milliseconds** before the pirates track can be played again. If no config option is specified, it defaults to 5 minutes.
