### ISSUE TITLE
YouTube links can't be found

### ISSUE THREAD

**Issue by Permanently** [yummypasta/MinecraftManhunt#26]
## Describe the bug
Basically, two songs (timesup and preparing-danger) can't be played due to copyright strikes.

## Potential Causes
/music auto

## Environment Info
**Plugin version:** 1.3.3

**Bukkit/Spigot server version:** 
Not applicable, but here you go anyway
Tuinity version git-Tuinity-"957a2ef" (MC: 1.16.4)

## Configuration file
N/A

## Server Logs
```
[18:36:21 WARN]: [MinecraftManhunt] Track preparing-danger not found: https://www.youtube.com/watch?v=CYcTNDXUOoY
[18:36:26 WARN]: [MinecraftManhunt] Track timesup not found: https://www.youtube.com/watch?v=dkqslkBUY6E
```

## Anything else?
¯\_(ツ)_/¯

**Comment by yummypasta** [comment]
Released in [1.3.3.1](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.3.3.1)
