### ISSUE TITLE
Config to enable/disable auto spectator mode

### ISSUE THREAD

**Issue by AncientZarko** [yummypasta/MinecraftManhunt#28]
## Description
Describe your proposed feature!
Add an option to disable the speedrunners being set to spectator automatically.

**Comment by yummypasta** [comment]
Published in release [1.3.3.3](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.3.3.3). I'm not going to publish this on the Bukkit/Spigot websites since it's such a minor change.
