### ISSUE TITLE
Update on Waterfall/BungeeCord Support

### ISSUE THREAD

**Issue by AncientZarko** [yummypasta/MinecraftManhunt#29]
Not much of a feature request, but.
The plugin does not work with offline-mode, and that is fine.
If the "Bungee" boolean is enabled in Spigot.yml, the plugin can correctly pull the data it needs from Bungee.
I reported this thinking it was a problem with the plugin when it really was a problem with my config.
TLDR: Plugin works with Bungee, just don't be a brainlet.

**Comment by yummypasta** [comment]
Glad it works! I'm going to add this info into #27 just in case other people have the same problem.
