### ISSUE TITLE
Add support for target selectors

### ISSUE THREAD

**Issue by AncientZarko** [yummypasta/MinecraftManhunt#30]
## Description
Add support for target selectors mainly @r, to randomly select someone as speedrunner/hunter.
This plugin is quickly on it's way to becoming the best manhunt plugin, and I feel this would make it better for servers trying to automate the setup process (ME)

**Comment by yummypasta** [comment]
Thanks for the suggestion @AncientZarko! I'll try to add this when I get a bit of time to work on the plugin, but for now to get a random player you can do
```
/say @r
```
and assign the team to whoever was put in chat!

**Comment by AncientZarko** [comment]
Hello! I found a way to get support for target selectors!
https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/
This can do what I need.
You should still support it natively at some point, but it shouldn't be a priority.
