### ISSUE TITLE
Compass not working

### ISSUE THREAD

**Issue by galpodlipnik1** [yummypasta/MinecraftManhunt#35]
## Describe the bug
 when u start the compass tracks spawn and says tracking player null. Fix the issue

**Comment by yummypasta** [comment]
Hello @galpodlipnik1,

Please make sure `online-mode` in server.properties is set to `true`. Otherwise the plugin will not work.

If this does not fix the problem, please post your full server logs so I can find the bug.

**Comment by yummypasta** [comment]
Support for offline mode has been added in [version 1.3.3.4](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.3.3.4)!
