### ISSUE TITLE
Port to 1.15.2?

### ISSUE THREAD

**Issue by bobland1** [yummypasta/MinecraftManhunt#38]
I would like to use this in conjunction with the terminator mod, as the automatic music in this is quite cool. Is there anyway you could port this over rto 1.15.2 or migrate it with [this ](https://www.spigotmc.org/resources/the-terminator-dream-video-tutorial.79887)

**Comment by yummypasta** [comment]
Sorry, the plugin uses the 1.16 Bukkit API and would take a lot of time to create and manage a 1.15 version. However, if you know Java, feel free to make a fork and edit the code to make it 1.15 compatible!

**Comment by bobland1** [comment]
I dont know how todo java, I do know c# though. How much work is it to get it to work?

**Comment by bobland1** [comment]
As for maintaining it, Im fine with it not being maintained. I will happily maintain it, its only for personal use. 

Either some help on how to port it to 1.15.2 or if you would, that would be great :)
