### ISSUE TITLE
Commands not being commands

### ISSUE THREAD

**Issue by Spuuk** [yummypasta/MinecraftManhunt#4]
When i try to do /start or add a speedrunner it does not recognize them as commands. I'm not sure if this is because I am on the server by myself while I test the plugin but I'm still going to post this just in case

**Comment by yummypasta** [comment]
Hi @Spuuk ,

This is most likely an installation issue. Please run the `/plugins` command and see if MinecraftManhunt is listed.

If not, please make sure the `.jar` file is in the plugins folder.

**Comment by Spuuk** [comment]
I just checked and it is listed but the command still isn't recognized

**Comment by yummypasta** [comment]
Alright. Can you please provide:
1. Any errors that show in the console when you start up your server
2. The version of Bukkit/spigot you're using
3. Your `config.yml` file for the plugin

Thank you!
