### ISSUE TITLE
Option to change /end command in config

### ISSUE THREAD

**Issue by zMario34** [yummypasta/MinecraftManhunt#47]
Can you add an option to modify end command? If I do /end my bungeecord server close xd

**Comment by yummypasta** [comment]
For now you can use namespaced commands:
```
/minecraftmanhunt:end
```
(or something like that, can't remember right now!)

**Comment by Permanently** [comment]
If you use `commands.yml`, you can change it to a different command. For example, if you wanted to change it to /endgame:
```yaml
  endgame:
  - end
```
