### ISSUE TITLE
Help with the source code

### ISSUE THREAD

**Issue by zMario34** [yummypasta/MinecraftManhunt#49]
Hey, I'm new to java code, I've imported all the maven and the plugin works, but the discord API don't works. is there a precise method to import the github project to eclipse? I would like to change the plugin messages simply

That is the error that appears on start in console:
https://pastebin.com/FkRy0Bqh

**Comment by yummypasta** [comment]
The plugin uses Maven to handle all dependencies. Maven stores all dependencies in the _pom.xml_ file, so your IDE should give you an option to download all the required packages specified in that file. 

I use IntelliJ for development and
I'm not sure how to do this in Eclipse, but if you Google how to set up Bukkit/Spigot with Maven in Eclipse there should be some guides to help.

**Comment by yummypasta** [comment]
Sorry, just read your issue again and you said that everything works except for Discord (which would be the JDA library). If I recall correctly I had to shade that plugin— make sure you included the file in the resources folder called `mavrn-shade-plugin-3.2.4.jar`.

**Comment by yummypasta** [comment]
Closing issue as stale— please reopen and provide more info if you are still having trouble!
