### ISSUE TITLE
Remove roles command

### ISSUE THREAD

**Issue by KiwiGexx** [yummypasta/MinecraftManhunt#5]
Adding roles and playing was super easy, but we ran into trouble trying to remove the roles. There isn't a command for it. Please help.

**Comment by Spuuk** [comment]
Isn't the command just /[role] remove [name]

**Comment by yummypasta** [comment]
Hi @KiwiGexx ,

The plugin doesn't currently have a remove roles feature but it's on my todo list. I'll add it in the next update!

**Comment by yummypasta** [comment]
Implemented in [release 1.2.1](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.2.1)!
