### ISSUE TITLE
Make /end restart and delete world

### ISSUE THREAD

**Issue by larssieboy18** [yummypasta/MinecraftManhunt#52]
## Description
Describe your proposed feature!

Hi there,

As it is really boring to play manhunt on the same map/seed multiple times, what we now do is stop the server, delete the world folders and restart. Would it be possible to add a function so that the /end command actually deletes the world folders and restarts the server.
Alternatively, it could also work if a new command, like /manhunt:restart or /manhunt:reset would just tp everyone far away, although that might mess up the ender portal placements.

**Comment by yummypasta** [comment]
I think this proposed feature would be overstepping the bounds of the plugin... agree with @Permanently that it could have destructive consequences. I'm marking this as wontfix, but please feel free to make your own fork of the plugin with this feature!

**Comment by larssieboy18** [comment]
Just in case anyone wants a plugin that does this: https://www.spigotmc.org/resources/resetworldreboot.81607/ and set the worlds
