### ISSUE TITLE
Compass Tracking

### ISSUE THREAD

**Issue by rieling** [yummypasta/MinecraftManhunt#58]
Is there a way you could make the compass stop tracking when getting to close to the runner
I was watching a dream video where they didnt know exactly where he went when he dug down and i was playing with my friends and i kept getting constantly just pinpointed my exact location is there a way we could set the compass to not work if the runners were a certain distance from the speedrunner like 10 to 50 blocks

**Comment by yummypasta** [comment]
The goal of this plugin is to recreate the game used in Dream's videos; I don't think such a mechanic is implemented in his plugin. I'm going to close this issue as out of scope, but feel free to fork the code and implement this!

**Comment by rieling** [comment]
I would love to fork the code i actually tried that originally i program in c# some and though i could but i now know that java is a whole nother playing field and im not sure even what org.____ are
if there was a simple way to mess with your compass code could you maybe even direct me on how to get there?

**Comment by yummypasta** [comment]
The plugin uses Maven, a dependency manager which allows you to use libraries without having to store them within your codebase. To pull these libraries from the Internet, you're going to have to have your IDE sync the libraries to your local development environment, then run the package command to compile everything into a jar.

[Here's a tutorial](https://www.spigotmc.org/wiki/creating-a-plugin-with-maven-using-intellij-idea/#compiling) on how to _create_ a plugin with Maven, but if you read through you'll get a sense of how it works!
