### ISSUE TITLE
compass issue

### ISSUE THREAD

**Issue by amasoudi861** [yummypasta/MinecraftManhunt#60]
## Describe the bug
the bug is about the compass just show the spawn when click right on and select the player it just wont work
## Potential Causes
i gave the compass too everybody then I asked the speedrunner to drop it
## Environment Info
**Plugin version:**
1.3.2
**Bukkit/Spigot server version:** 
1.16.4
## Configuration file
Sending us your plugin `config.yml` file may help in diagnosing the issue. Paste the contents of the plugin's config file here: (feel free to omit your Discord token for security reasons)
```yaml
Paste your config.yml file here
```

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:there is no error
```
Paste relevant console warnings/errors here
```

**Comment by yummypasta** [comment]
Please make sure `online-mode` in server.properties is set to `true`! If that doesn't work, please provide your configuration file and server logs as requested so I can diagnose the issue. Thanks.

**Comment by yummypasta** [comment]
Closing this issue as stale. If the problem is not resolved, please re-open and include requested info.
