### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by Thorshammers** [yummypasta/MinecraftManhunt#61]
## Description 
I was thinking on how to make it automatically tp people to a game from a hub and how to automatically start a game and choose a role without using commands .how would we do this and would you guys  consider adding it in

**Comment by yummypasta** [comment]
While this feature request is out of the scope of the plugin, you may be able to figure something out using command blocks / another custom plugin, possibly using target selectors (which are not natively supported, but you can use something as detailed in #30).
