### ISSUE TITLE
Team chat by default

### ISSUE THREAD

**Issue by larssieboy18** [yummypasta/MinecraftManhunt#64]
## Description
Hi!

As the plugin uses vanilla teams by default and `/teammsg` puts something for only the teammembers to see, I was wondering if it was possible to enable `/teammsg` by default, so that you cannot send something in chat and accidentally also send it to your opponents. It might be best to add it in the config so people can toggle if they want to have this function or not?

If you are aware of another plugin that would make this possible, then please let me know, as I have been looking for ages for this and would really like to see it implemented!

**Comment by yummypasta** [comment]
Hi @larssieboy18, thanks for using the plugin.

I think a feature like this would be out of scope for this plugin, but I've found this to be annoying too and I may consider making a standalone plugin that does this, since the manhunt plugin uses builtin scoreboard teams!

**Comment by larssieboy18** [comment]
Thanks :D This plugin (that is outdated) might be useful to take a look at I guess, as it is open source :) https://www.spigotmc.org/resources/team-chat-scoreboard.18955/

**Comment by yummypasta** [comment]
@larssieboy18 I just finished developing the plugin you have requested, [here's the release](https://github.com/yummypasta/AutoTeamChat/releases/tag/v1.0.0)!

**Comment by larssieboy18** [comment]
Thank you so much :D Will use it and if there are any issues, I will let you know (in that repo)!
