### ISSUE TITLE
Compass circling in the nether

### ISSUE THREAD

**Issue by Feedyyy** [yummypasta/MinecraftManhunt#66]
## Describe the bug
When a runner goes into the nether, the compass indicates the portal used. but when the hunter enters the Nether, the compass turns in all directions and therefore impossible to track them

## Potential Causes
I think it's just a feature of minecraft that needs to be fixed with this plugin
## Environment Info
**Plugin version:** 1.3.3.6

**Bukkit/Spigot server version:** 1.16.1

## Configuration file
```
# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
compassEnabledInNether: true
setRunnersToSpecOnDeath: true
sendUsageData: true
huntersColor: '&c'
runnersColor: '&a'
spectatorsColor: '&b'
enableDiscord: false
discordToken: XXXXX
ip: a minecraft server
processDiscordCommands: true
discordServerId: XXXXX
musicChannelId: XXXXX
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: 27eeb933-7a55-47b4-9f27-334db24cdf4d
```

## Server Logs

```
No warning / error 
```

## Anything else?
x

**Comment by yummypasta** [comment]
Hello, thanks for submitting this issue. I've tested the plugin and saw this feature working, but I'll re-verify to make sure it hasn't broken.

**Comment by Permanently** [comment]
Yeah, had this issue a while ago as well. Just never mentioned it as I thought it was intentional.

**Comment by yummypasta** [comment]
Sorry, I can't reproduce this bug for some reason! Your config file looks set up properly and everything... next time this occurs please save the entire server logs, upload them, and reopen this issue so I can see what's going on!
