### ISSUE TITLE
Whenever I play music using this plugin on my cracked server, me and my friends are kicked again and again and music also never plays

### ISSUE THREAD

**Issue by ARINDAM576** [yummypasta/MinecraftManhunt#68]
Whenever I play music using this plugin on my cracked server, me and my friends are kicked again and again and music also never plays. I have correctly edited the config.yml file but then also, problem exists. It shows something big and un-understandable in the logs. I have uploaded the config.yml file but in txt format cuz GitHub was saying that we don't support this format.

I did nothing! I just have cracked server and I used /music auto and /music approaching and the problem began. It happens everytime I play music on my server.

Plugin version: MinecraftManhunt-1.3.3.6.jar

Bukkit/Spigot server version: 1.16.5 (Paper) with Java 8 (1.8.0_282)

## Configuration file (config.yml)

# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 30
compassEnabledInNether: true
setRunnersToSpecOnDeath: false
sendUsageData: true
huntersColor: '&c'
runnersColor: '&a'
spectatorsColor: '&b'
enableDiscord: true
discordToken: [Edited out by project maintainer]
ip: de11.falix.gg:27132
processDiscordCommands: true
discordServerId: 819066874624081921
musicChannelId: 819066874624081927
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: e424c186-36e2-4f7c-81a3-325d413161a3

Paste your config.yml file here
```

[Edited out by project maintainer—Discord bot token compromised]



## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:

IT WAS TOO LONG AND IT WAS SHOWING MAXIMUM CHARACTER LIMIT EXCEEDED, SO I CANNOT PUT IT HERE, JUST CHECK IT IN THE FILE ATTACHED BELOW, SORRY HEHE.



```
Paste relevant console warnings/errors here
```
[2021-04-30-3.log](https://github.com/yummypasta/MinecraftManhunt/files/6439051/2021-04-30-3.log)

Please help me as quick as possible cuz I need those Dream Songs!!!!!
BTW THE BEST MANHUNT PLUGIN THIS IS!!!!! THANKS A LOT.

**Comment by ARINDAM576** [comment]
PLEASE SOLVE MY PROBLEM AS FAST AS POSSIBLE, BTW BEST MANHUNT PLUGIN, THANKS!

**Comment by yummypasta** [comment]
Hello, thank you for uploading server logs. I'll take a look, but in the mean time, you included your Discord bot token in your issue; I just edited it out, but please consider it as compromised and change it ASAP. Making a bot token public is a serious security issue and if someone malicious gets their hands on it, they are able to nuke every server the bot is in.

**Comment by yummypasta** [comment]
I've found the issue (same one as in #65). This issue has been fixed in plugin version 1.3.3.7, which you can get [here](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.3.3.7). Please close this issue if this fixes your problem!

**Comment by ARINDAM576** [comment]
0mg you replied so fast! I will try out the new version and reply here, thank you!!!!!!!!
AND SORRY FOR THOSE LONG LOGS AND BOT TOKEN HEHE

**Comment by ARINDAM576** [comment]
BUT HEY, I AM CHECKING THE FILES TAB IN THE DEV.BUKKIT WEBSITE, THERE IS NO VERSION 1.3.3.7, ONLY TILL 1.3.3.6

**Comment by yummypasta** [comment]
Bukkit is still in the process of reviewing the new file. Get the new version on the releases page:
https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.3.3.7

**Comment by ARINDAM576** [comment]
oh thanks ;D

**Comment by yummypasta** [comment]
Closing this issue. If you are still experiencing problems, please reopen it.
